# Generated by Django 4.1.2 on 2022-11-10 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
