# Generated by Django 4.1.2 on 2022-10-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creation_datetime',
        ),
    ]
